### ISSUE TITLE
程序崩溃，进程退出

### ISSUE THREAD

**Issue by youngqqcn** [PerrorOne/miner-proxy#20]
```
unexpected fault address 0x1017e7c39
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1017e7c39 pc=0x466849]

goroutine 38289 [running]:
runtime.throw({0x7e8145, 0x81000009})
        /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc0002494c0 sp=0xc000249490 pc=0x435491
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:742 +0x2f6 fp=0xc000249510 sp=0xc0002494c0 pc=0x44abf6
runtime.memmove()
        /usr/local/go/src/runtime/memmove_amd64.s:410 +0x489 fp=0xc000249518 sp=0xc000249510 pc=0x466849
runtime.concatstrings(0xc0001d0200, {0xc0002495b0, 0x3, 0x40e854})
        /usr/local/go/src/runtime/string.go:52 +0x17c fp=0xc000249590 sp=0xc000249518 pc=0x44f67c
runtime.concatstring3(0x203000, {0x7e825d, 0xc0001c73b0}, {0x865770, 0x40c8b4}, {0x807e7cb6, 0x432c90})
        /usr/local/go/src/runtime/string.go:63 +0x6f fp=0xc0002495f0 sp=0xc000249590 pc=0x44f8af
net.(*OpError).Error(0xc00045cc30)
        /usr/local/go/src/net/net.go:470 +0x58 fp=0xc000249648 sp=0xc0002495f0 pc=0x5c3638
fmt.(*pp).handleMethods(0xc0001160d0, 0xfe7df0a8)
        /usr/local/go/src/fmt/print.go:620 +0x23c fp=0xc0002498f8 sp=0xc000249648 pc=0x4dbf5c
fmt.(*pp).printArg(0xc0001160d0, {0x7a1280, 0xc00045cc30}, 0x76)
        /usr/local/go/src/fmt/print.go:709 +0x693 fp=0xc000249998 sp=0xc0002498f8 pc=0x4dcc53
fmt.(*pp).doPrintf(0xc0001160d0, {0x7f37b5, 0x1f}, {0xc0006b0020, 0xc00049a000, 0x0})
        /usr/local/go/src/fmt/print.go:1026 +0x288 fp=0xc000249a90 sp=0xc000249998 pc=0x4df508
fmt.Sprintf({0x7f37b5, 0x1f}, {0xc0006b0020, 0x1, 0x1})
        /usr/local/go/src/fmt/print.go:219 +0x59 fp=0xc000249ae8 sp=0xc000249a90 pc=0x4d9919
go.uber.org/zap.getMessage({0x7f37b5, 0xa}, {0xc0006b0020, 0x0, 0xc00038cb58})
        /root/goProject/pkg/mod/go.uber.org/zap@v1.20.0/sugar.go:238 +0x74 fp=0xc000249b20 sp=0xc000249ae8 pc=0x6e05b4
go.uber.org/zap.(*SugaredLogger).log(0xc000010020, 0x1, {0x7f37b5, 0x1f}, {0xc0006b0020, 0x1, 0x1}, {0x0, 0x0, 0x0})
        /root/goProject/pkg/mod/go.uber.org/zap@v1.20.0/sugar.go:225 +0x9d fp=0xc000249b60 sp=0xc000249b20 pc=0x6e047d
go.uber.org/zap.(*SugaredLogger).Warnf(...)
        /root/goProject/pkg/mod/go.uber.org/zap@v1.20.0/sugar.go:143
go.uber.org/zap.(*SugaredLogger).Warnf-fm({0x7f37b5, 0xc000115020}, {0xc0006b0020, 0x7ff52cbb6f30, 0x50})
        /root/goProject/pkg/mod/go.uber.org/zap@v1.20.0/sugar.go:142 +0x55 fp=0xc000249bc0 sp=0xc000249b60 pc=0x6e8f15
miner-proxy/pkg.outByLog(0x1, {0x7f37b5, 0x1f}, {0xc0006b0020, 0x1, 0x1})
        /root/miner-proxy/pkg/log.go:98 +0x18b fp=0xc000249c80 sp=0xc000249bc0 pc=0x6e8bcb
miner-proxy/pkg.Warn(...)
        /root/miner-proxy/pkg/log.go:110
miner-proxy/proxy.(*Proxy).err(0xc00074e400, {0x7f37b5, 0x1f}, {0x869640, 0xc00045cc30})
        /root/miner-proxy/proxy/proxy.go:84 +0x105 fp=0xc000249cd0 sp=0xc000249c80 pc=0x70d3e5
miner-proxy/proxy.(*Proxy).ReadEncryptionSendPlaintext.func1({0xc000128078, {0xc000242000, 0x7e79c5, 0x1}})
        /root/miner-proxy/proxy/proxy.go:231 +0x2ea fp=0xc000249d88 sp=0xc000249cd0 pc=0x70e60a
miner-proxy/proxy.(*Package).Read(0xc00038ce50, {0x869680, 0xc000128078}, 0xc00038ce68)
        /root/miner-proxy/proxy/package.go:167 +0x2be fp=0xc000249e28 sp=0xc000249d88 pc=0x70c99e
miner-proxy/proxy.(*Proxy).ReadEncryptionSendPlaintext(0x40c5ea, {0x869680, 0xc000128078}, {0x8696a0, 0xc000128038})
        /root/miner-proxy/proxy/proxy.go:212 +0x91 fp=0xc000249ea8 sp=0xc000249e28 pc=0x70e2b1
miner-proxy/proxy.(*Proxy).ReadEncryptionSendPlaintext-fm({0x869680, 0xc000128078}, {0x8696a0, 0xc000128038})
        /root/miner-proxy/proxy/proxy.go:210 +0x49 fp=0xc000249ee0 sp=0xc000249ea8 pc=0x70f789
miner-proxy/proxy.(*Proxy).pipe(0xc00074e400, {0x7ff5040b18d8, 0xc000128078}, {0x7ff5040b18d8, 0xc000128038})                                                                                 
        /root/miner-proxy/proxy/proxy.go:346 +0x2a6 fp=0xc000249fa8 sp=0xc000249ee0 pc=0x70f446                                                                                               
miner-proxy/proxy.(*Proxy).Start·dwrap·5()                                                                                                                                                    
        /root/miner-proxy/proxy/proxy.go:65 +0x36 fp=0xc000249fe0 sp=0xc000249fa8 pc=0x70d0b6                                                                                                 
runtime.goexit()                                                                                                                                                                              
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000249fe8 sp=0xc000249fe0 pc=0x465561                                                                                           
created by miner-proxy/proxy.(*Proxy).Start                                                                                                                                                   
        /root/miner-proxy/proxy/proxy.go:65 +0x3ef        

....
```

**Comment by PerrorOne** [comment]
你使用的版本?以及系统信息?

**Comment by youngqqcn** [comment]
tag, v0.3.5

**Comment by youngqqcn** [comment]
centos

**Comment by PerrorOne** [comment]
是偶发性的吗?还是只要运行就报错?

**Comment by youngqqcn** [comment]
> 是偶发性的吗?还是只要运行就报错?

运行了一段时间
